# Generated by Django 3.0.3 on 2020-07-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20200718_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='status',
            field=models.CharField(choices=[('PR', 'private'), ('RE', 'release')], default='PR', max_length=2, verbose_name='ステータス'),
        ),
    ]
