# Generated by Django 3.0.3 on 2020-07-21 12:11

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20200718_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='body',
            field=markdownx.models.MarkdownxField(verbose_name='本文'),
        ),
    ]
