# Generated by Django 3.0.3 on 2020-07-22 05:26

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20200721_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='body',
            field=markdownx.models.MarkdownxField(verbose_name='Markdown形式で本文を書こう'),
        ),
    ]
