# Generated by Django 3.0.3 on 2020-07-23 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20200722_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='status',
        ),
    ]
